all:
  children:
    india:
      hosts:
        app-india-1:
          ansible_host: 10.10.1.10
        app-india-2:
          ansible_host: 10.10.1.11
        db-india-1:
          ansible_host: 10.10.1.20
      vars:
        region: india
        timezone: Asia/Kolkata

    china:
      hosts:
        app-china-1:
          ansible_host: 10.20.1.10
        app-china-2:
          ansible_host: 10.20.1.11
        db-china-1:
          ansible_host: 10.20.1.20
      vars:
        region: china
        timezone: Asia/Shanghai

    usa:
      hosts:
        app-usa-1:
          ansible_host: 10.30.1.10
        app-usa-2:
          ansible_host: 10.30.1.11
        db-usa-1:
          ansible_host: 10.30.1.20
      vars:
        region: usa
        timezone: America/New_York

    app_servers:
      children:
        india:
        china:
        usa:
      vars:
        ansible_user: deploy
        app_service_name: nexusguard-app

    db_servers:
      hosts:
        db-india-1:
        db-china-1:
        db-usa-1:
      vars:
        ansible_user: deploy
        db_service_name: postgresql
